apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-wjxl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-wjxl
    app.kubernetes.io/part-of: my-app-4
  name: devfile-sample-go-basic-wjxl
  namespace: burrzinga-hac-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-wjxl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-wjxl
    spec:
      containers:
      - image: quay.io/stonesoupuicluster/burrzinga-hac-tenant/my-app-4/devfile-sample-go-basic-wjxl@sha256:3f548b21f13f33443291252b78c83e9bc0163457b09285882c4617a10376d215
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
